Lesson11 devise
vadimzhukov/TestGuru pull request #12
Opened 2022-09-20 10:19 UTC by vadimzhukov

1. Реализуйте аутентификацию в проекте при помощи библиотеки Devise
2. Сделайте управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализуйте перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратором назначайте его в качестве автора теста

Усложненное задание:

При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить флэш-сообщение "Привет, <имя пользователя>!"

2022-09-20 16:48 UTC, BubuntuClu requested changes

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'Вы не являетесь администратором, доступ запрещен' unless current_user.is_a?(Admin)
обавь метод в модель `User` который будет проверять является ли пользователь админом. `current_user.admin?`

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  def start
в админке старт не нужен

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_parameters)
>При создании нового теста администратором назначайте его в качестве автора теста

не сделал

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :author_id, :category_id).merge(author_id: current_user.id)
а, вот как ты сделал. нет, это костыль. используй асссоциацию созданных тестов
в параметрах не должно быть `author_id`

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
почему тут `current_user` когда тебе аргументом приходит `resource`? почему ты решил не использовать этот аргумент?

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
`resource.admin?`

2022-09-20 16:48 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
може этот колбэек вынести все-таки в `ApplicationController`?

2022-09-20 19:06 UTC, vadimzhukov commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'Вы не являетесь администратором, доступ запрещен' unless current_user.is_a?(Admin)
done

2022-09-20 19:06 UTC, vadimzhukov commented on app/controllers/admin/tests_controller.rb
> +  def start
fixed

2022-09-20 19:08 UTC, vadimzhukov commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_parameters)
)) сделал, но по другому. Исправил

2022-09-20 19:09 UTC, vadimzhukov commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :author_id, :category_id).merge(author_id: current_user.id)
done

2022-09-20 19:22 UTC, vadimzhukov commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
fixed

2022-09-21 07:03 UTC, BubuntuClu requested changes

2022-09-21 07:03 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test.author_id = current_user.id
это тоже костыль. через ассоциацию надо сделать

2022-09-21 07:03 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :author_id, :category_id)
author_id не должно быть тут

2022-09-21 15:25 UTC, vadimzhukov commented on app/controllers/admin/tests_controller.rb
> +    @test.author_id = current_user.id
fixed

2022-09-21 15:25 UTC, vadimzhukov commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :author_id, :category_id)
fixed

2022-10-14 21:21 UTC, merged