L14 api
vadimzhukov/TestGuru pull request #15
Opened 2022-10-28 17:40 UTC by vadimzhukov

Добавлена возможность сохранения gist в процессе прохождения тестов с возможностью для администратора просматривать весь список созданных gist.

2022-10-29 15:30 UTC, VidgarVii requested changes

2022-10-29 15:30 UTC, VidgarVii commented on .gitignore
> +/config/local_env.yml
для переменных окружения в разработке используют gem 'dotenv-rails' Советую разобраться именно в нём

2022-10-29 15:30 UTC, VidgarVii commented on .gitignore
> +/config/local_env.yml
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2022-10-29 15:30 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
он ведь больше не используется. Лучше удалить

2022-10-29 15:30 UTC, VidgarVii commented on app/TEMP/temp.json
> +{\"url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1\",\"forks_url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1/forks\",\"commits_url\":\"https://api.github.c
не уверен, что этот файл нужен проекту

2022-10-29 15:30 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Gist это ресурс. Значит согласно rails way и REST для создания ресурса  и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2022-10-29 15:30 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if @gist.save
Гист создаёшь сам, без входящих параметров от юзера. Соответственно если по каким-то причинам гист не был создан, то это уже баг в коде. И видеть этот баг юзеру нет смысла. А следует разобраться и починить ошибку

2022-10-29 15:30 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
GitHubClient и есть октокит. А GistQuestionService адаптер под него. Новый класс не имеет смысла создавать. Вот если бы писал клиент с нуля используя фарадей, то тогда да

2022-10-29 15:30 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
установка "нил" в аргументах - это возможно не лучшее решение
я бы для такого случая порекомендовал вариант установки дефолта, к примеру, такой:
```ruby
def initialize(question, client = default_client)
  ...
  @client = client
end
```
далее можно определить в методе `default_client` "дефолтного клиента"

```ruby
private

def default_client
  Octokit::Client.new(access_token: GITHUB_GIST_TOKEN)
end
```

2022-10-29 15:30 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
```ruby
def gist_content
  content = [@question.body]
```
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2022-10-29 15:30 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
Метод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct 
Минус твоего подхода в том, что если придётся менять гем, то придётся исправлять код в разных местах проекта. А класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента. И если придётся менять этот хттп клиент, то рефакторигну подвергнется только сервис  GistQuestionService

2022-10-29 15:30 UTC, VidgarVii commented on config/application.rb
> +    end
в этом коде не будет смысла, если использовать dotenv-rails
А сейчас это похоже на проблему в безопасности

2022-10-29 15:30 UTC, VidgarVii commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= link_to gist.question.body.slice(0,24), admin_question_path(gist.question)%></td>
здесь лучше использовать хелпер `truncate` - [вот небольшой пост про него](https://makandracards.com/makandra/53287-heads-up-rails-offers-two-similar-means-for-text-truncation)

2022-10-30 10:29 UTC, vadimzhukov commented on app/TEMP/temp.json
> +{\"url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1\",\"forks_url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1/forks\",\"commits_url\":\"https://api.github.c
fixed

2022-10-30 10:29 UTC, vadimzhukov commented on Gemfile
> +gem 'faraday'
fixed

2022-10-30 10:33 UTC, vadimzhukov commented on app/controllers/test_passages_controller.rb
> +    flash_options = if @gist.save
не понял суть твоего замечания. Если речь про то, что я во flash фиксирую aler: то я же не показываю пользователю текст или код ошибки, а просто выдаю ошибку создания во флеш сообщении если по каким то причинам гист не сохранился.

2022-10-30 10:34 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
тут я следую архитектуре, которая описывается в лекции, она позволяет в будущем замнить октокит на другой клиент, не изменяя GistQuestionSerice

2022-10-30 10:36 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
при сохранении архитектуры где все таки используется библиотечный клас GitHubCLient стоит оставить текущую реализацию как по мне

2022-10-30 10:49 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  end
ок, это  *args оператор?

2022-10-30 11:10 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  end
второй абзац комментария обеспечивается выделением отдельного класса GitHubClient.
Про Struct интересно, действительно правильно четко определить какие именно переменные можно использовать как геттеры для возвращаемого октокитом объекта при create_gist. Но как это сделать при наличии  
def create_gist(params)
    @http_client.create_gist(params)
  end

?

2022-10-30 11:14 UTC, vadimzhukov commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= link_to gist.question.body.slice(0,24), admin_question_path(gist.question)%></td>
fixed

2022-10-30 11:22 UTC, vadimzhukov commented on .gitignore
> +/config/local_env.yml
ok, спасибо за наводуц на dotenv-rails

2022-10-30 11:24 UTC, vadimzhukov commented on app/controllers/test_passages_controller.rb
> +  def gist
вот тут очень большой вопорос у меня - перекидывать пользователя на другой ресурс (gist) для создания гиста и потом возвращаться к test_passage стоит ли? 
Если все таки делать так, то как передать в link_to объект текущего test_passage чтобы исползовать его для ассоциации с создаваемым гистом и потом вернуть пользователя на прохождение теста с нужной точки?

2022-10-30 11:25 UTC, vadimzhukov commented on .gitignore
> +/config/local_env.yml
fixed

2022-11-01 10:36 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
достаточно передать test_passage_id
а после создания гист отправляь юзера на show test passage. Должна открыться страница текущего вопроса

2022-11-01 10:37 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if @gist.save
если гист не сохранился в базе, то это уже баг, который надо чинить, а не показывать юзеру

2022-11-01 10:39 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
в скринкасте создавался хттп клиент для работы с апи с нуля, используя хттп клиент фарадей. Это верный подход. 
Октокит же уже является клиентом для апи с гитхабом. Октокит уже внитри себя использует какой-нибудь хттп клиент. Зачем надо 10 раз оборачивать какой-то класс не понятно. Адаптер над актокит будет сервис. Это достаточно

2022-11-01 10:39 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
не понял вопроса

2022-11-01 10:41 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
результат create_gist передать в контруктор структуры. И выдать в контроллер только те методы, которые нужны для создания гист в базе. Или вообще писать гист в базу в этом сервисе. И нужен только 1 метод success? для проверки успешности выполнения результата в контроллере

2022-11-02 09:46 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  end
Сделал по второму варианту - логику создания и сохранения в БД поместил в сервис

2022-11-02 09:46 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
ок, переделал

2022-11-02 09:47 UTC, vadimzhukov commented on app/controllers/test_passages_controller.rb
> +    flash_options = if @gist.save
ок, оставил только notice

2022-11-02 09:50 UTC, vadimzhukov commented on app/controllers/test_passages_controller.rb
> +  def gist
done

2022-11-02 09:50 UTC, vadimzhukov commented on config/application.rb
> +    end
fixed

2022-11-02 17:03 UTC, BubuntuClu requested changes

2022-11-02 17:03 UTC, BubuntuClu commented on app/controllers/TEMP/temp.json
> +{\"url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1\",\"forks_url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1/forks\",\"commits_url\":\"https://api.github.c
этот файл надо удалить из ПРа, это какой-то мусор

2022-11-02 17:03 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +    new_gist = GistQuestionService.new(@test_passage)
new_gist - это объект сервиса, а не новый гист. нейминг вносит смуту

2022-11-02 17:03 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +    gist = new_gist.save
обычно "главный метод" сервиса называют `call`

2022-11-02 17:03 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +    if gist.persisted?
а если он не персистед? надо уведомить пользователя что произошла ошибка. 

тут у меня противоположное мнение с предыдущим ментором. не информировать пользователя о провале, это плохо, потому что пользователь будет думать что все прошло успешно. можно не выдавать конкретную ошибку почему упало, а просто "попробуйте позже", типа того что у тебя было

2022-11-02 17:03 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +  def create_structured_gist
в такой реализации не вижу смысла от структуры. ты просто из одного объекта перекладываешь часть инфы в другой. я так понял структура предполагалась для исопльзования если ты из сервиса вернешь объект с данными о гисте созданном сервисом.

сейчас выглядит очень странно

2022-11-02 17:03 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @gist = @test_passage.gists.new({ url: result.html_url, gist_hash: result.id,
наличие объектов html_url и id не гарантирует тебе полной уверенности что гист был создан в гистхабе. там может быть что-то типа `error_url` или любая другая строка.

у октокита есть метод `last_response`, который тебе надо использовать и по статусу ответа понять как прошел запрос к гистхабу. метод `success?`, который тебе предложили, как раз на этой `last_response` проверке должен строится. делашеь запрос в гистхаб. проверяешь успещность, при успехе сохраняешь у себя.

сейчас у тебя в любом случае делается запрос в БД на попытку сохранения гиста, при провале ты лишний раз дергаешь БД

2022-11-02 17:03 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @gist.save
почему у тебя в этом месте используется инстанс переменная?

2022-11-02 17:03 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +  def save
если следовать поведению рельсы, то метод `save` возвращает `true/false` значения. и может быть большим сюрпризом что твой `save` вернет объект.

был коммент про то что метод стоит переименовать

2022-11-02 18:23 UTC, vadimzhukov commented on app/controllers/admin/gists_controller.rb
> +    gist = new_gist.save
fixed

2022-11-02 18:23 UTC, vadimzhukov commented on app/controllers/admin/gists_controller.rb
> +    if gist.persisted?
fixed

2022-11-02 18:25 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  def create_structured_gist
нет, структура добавлена для того, чтобы явно указать на геттеры id и html_url

2022-11-02 19:37 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  def create_structured_gist
как корректно поступить - возвращать структурированный объект или все таки Sawyer::Response ?

2022-11-02 19:38 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +    @gist = @test_passage.gists.new({ url: result.html_url, gist_hash: result.id,
Добавил анализ last_response , но success? добавил в структуру возвращаемую методом call сервиса. Это корректно?

2022-11-02 19:40 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +    @gist.save
атавизм видимо остался от предыдущих решений. fixed

2022-11-02 19:40 UTC, vadimzhukov commented on app/services/gist_question_service.rb
> +  def save
переименовал в call

2022-11-03 07:11 UTC, BubuntuClu commented on app/controllers/TEMP/temp.json
> +{\"url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1\",\"forks_url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1/forks\",\"commits_url\":\"https://api.github.c
файл не удалил

2022-11-03 07:11 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +  def create_structured_gist
структурированный

2022-11-03 07:11 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +    if gist&.success?
костыль конечно `&` впихивать. лучше вернуть объект ответа отдельно. и потом сервисом вызвать метод `success?` чтобы првоерить как прошел запрос. сейчас у тебя все в куче и надо логику костылить и делать ненужные действия(всегда пытаешься сохранить гист у себя в БД)

2022-11-03 12:09 UTC, vadimzhukov commented on app/controllers/TEMP/temp.json
> +{\"url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1\",\"forks_url\":\"https://api.github.com/gists/e0c7643ef5e7f2f4b72a1a335919e6a1/forks\",\"commits_url\":\"https://api.github.c
fixed

2022-11-03 19:20 UTC, merged