feat: добавлена сортировка по полю Название теста для таблицы админки…
vadimzhukov/TestGuru pull request #16
Opened 2022-11-06 06:43 UTC by vadimzhukov

… редактирования тестов и таблицы запуска тестов пользователем, добавлена фронтовая валидация ввода подтверждения пароля при регистрации

2022-11-06 16:05 UTC, BubuntuClu requested changes

2022-11-06 16:05 UTC, BubuntuClu commented on app/javascript/packs/utilities/input_check.js
> +  if (passwordConfirmInput) {
>Не информируйте пользователя если поле подтверждения пароля не содержит значения

этот пункт задания не учтен. если что-то ввести и потом очистить, то у тебя разметка останется;

сделай `return` с очищением если подтверждение пустое

2022-11-06 16:05 UTC, BubuntuClu commented on app/javascript/packs/utilities/sorting.js
> +    if (arrowUp.classList.contains('hide')) {
отступы поехали. выровняй код

2022-11-06 20:08 UTC, vadimzhukov commented on app/javascript/packs/utilities/sorting.js
> +    if (arrowUp.classList.contains('hide')) {
fixed

2022-11-06 20:09 UTC, vadimzhukov commented on app/javascript/packs/utilities/input_check.js
> +  if (passwordConfirmInput) {
fixed

2022-11-07 06:52 UTC, BubuntuClu commented on app/javascript/packs/utilities/input_check.js
> +  if (passwordConfirmInput) {
чтобы не оборачивать весь код в `if` сделай `return` если компонента нет.

2022-11-07 13:17 UTC, merged