feat: rewards for test passing
vadimzhukov/TestGuru pull request #19
Opened 2022-12-28 22:14 UTC by vadimzhukov

2022-12-29 06:54 UTC, BubuntuClu requested changes

2022-12-29 06:54 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    if @badge.save!
почему бэнг метод, да еще и без обработки ошибки?

2022-12-29 06:54 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +  def rewards
давай по ресту экшены называть. не вижу смысла в отдельном экшене, когда это покрывается методом `show`. какой смысл в отдельной странице?

2022-12-29 06:54 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.successfully = true if successful?
это лучше вынести в отдельный метод. `accept` отвечает только за прием правильных ответов, не стоит сюда подмешивать стороннюю логику

2022-12-29 06:54 UTC, BubuntuClu commented on app/services/reward_service.rb
> +    if @test_passage.successfully
смотри, ты выше выполняешь огромную кучу логики, чтобы инициализировать сервис, а поом бац, тест-то пройден не успешно и ты просто не запускаешь дальнейшую обработку. вся твоя инициализация пошла насмарку, но время и ресурсы ты уже потратил.
что если эту проверку вынести на уровень выше? перед вызовом сервиса проверять успех теста

2022-12-29 06:54 UTC, BubuntuClu commented on app/services/reward_service.rb
> +    @current_level = @test.level
при росте количества баджей и различных параметрах в них, этот код будет расширятся? тут будет такое полотное, которое устанешь проматывать)
надо придумать другой подход

2022-12-29 06:54 UTC, BubuntuClu commented on app/services/reward_service.rb
> +  end
тоже метод, претендующий на безграничный рост.
надо написать метод, который не будет меняться в зависимости от количества баджей и правил для них.

правила ессесно будут добавляться, тут никуда не дется

2022-12-29 06:54 UTC, BubuntuClu commented on app/services/reward_service.rb
> +      Badge.find_by(title: 'First try success')
ненадежный поиск. изменилось вдруг название и тебе надо лезть в код менять код.

2022-12-29 06:54 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/badges'
используй ресурс, не вижу смысла в кастомных путях

2022-12-29 06:54 UTC, BubuntuClu commented on config/routes.rb
> +  get 'badges/add', to: 'badges#add', as: 'add_badges'
и тут тоже, это же `create`

2022-12-29 06:54 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +  def add
почему вызов сервиса происходит тут, а не при проверке ответа на вопрос?

2022-12-29 06:57 UTC, BubuntuClu requested changes

2022-12-29 06:57 UTC, BubuntuClu commented on app/services/reward_service.rb
> +  def user_state
какая-то сложная логика. зачем все это считать за раз? дай каждому методу в обязанность доставать нужные данные самому. так код станет понятней, когда он разбит по контекстам, а не сразу все вывалено в портянке кода

2022-12-29 06:57 UTC, BubuntuClu commented on app/services/reward_service.rb
> +  def user_state
да и хэши тогда не нужны будут.
по сути по 1-2 запроса на метод потребуется. достать данные по пользователю и достать данные которые нужны для проверки правила(типа сколько тестов категории прошел пользователь и сколько всего тестов в категори), сравнил два массива и получаешь ответ, давать бейдж или нет

2023-01-09 17:53 UTC, vadimzhukov commented on app/controllers/users_controller.rb
> +  def rewards
тут нужно показать награды (список) именно данного пользователя, поэтому и спец страница в рамках вью пользователя и соответственно ресурс в контроллере.
Замечу, что по заданию у пользотеля должна быть возможность как посмотреть его зараюотанные награды, так и все возможные

2023-01-09 17:55 UTC, vadimzhukov commented on app/controllers/badges_controller.rb
> +  def add
потому что для бэйджей я сделал свой контроллер, его метод вызывается из TestPassageController:
def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.current_question
      render :show
    else
      redirect_to add_badges_path(id: @test_passage)
    end
  end

2023-01-09 17:55 UTC, vadimzhukov commented on app/controllers/admin/badges_controller.rb
> +    if @badge.save!
убрал бэнг

2023-01-09 18:00 UTC, vadimzhukov commented on app/models/test_passage.rb
> +    self.successfully = true if successful?
перенес в контроллер. Но в целом места где бы четко фиксировалось завершение прохождения явно нет, только в контроллере if на наличие нового текущего вопроса, что как по мне не красиво...

2023-01-10 07:23 UTC, BubuntuClu requested changes

2023-01-10 07:23 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +  def add
так не надо делать
ты из того контроллера, вызываешь этот контроллер, а потом тут о5 вызываешь первый контроллер. в чем смысл? в первом же контроллере сервис и вызывай

2023-01-10 07:23 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @badges = current_user.badges.select{|b| UserBadge.where("test_passage_id = ?", @test_passage.id).pluck('badge_id').include?(b.id)}
в чем смысл этого запроса? почему просто `current_user.badges` не подходит?
`where(test_passage_id: @test_passage.id)`

2023-01-10 07:23 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +  def rewards
для этого точно надо делать разные страницы? можно же на одной показать. вывести список всех наград и под ними написать что заработал, это вроде выглядить удобней

2023-01-10 07:23 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.successfully = true if successful?
эта штука не сохраняет состояние в БД. ты только объекту выставляешь это значение

2023-01-10 07:23 UTC, BubuntuClu commented on app/services/reward_service.rb
> +        BadgeRule.where(badge_id: badge).each do |badge_rule|
`badge.rules`? ассоциации не зря же задавал

2023-01-10 07:23 UTC, BubuntuClu commented on app/services/rules_service.rb
> +class RulesService
кажется что этот класс надо разбить по каждый бадж. сделать базовый `rule_service` и от него уже наследовать реализацию нужного баджа. слишком много методов получается и очень сложно в коде разбираться и с ростом количества баджей будет расширятся класс бескрайне

2023-01-10 08:39 UTC, vadimzhukov commented on app/controllers/test_passages_controller.rb
> +    @badges = current_user.badges.select{|b| UserBadge.where("test_passage_id = ?", @test_passage.id).pluck('badge_id').include?(b.id)}
смысл тут в том, чтобы по завершении прохождения теста показать бэджи, заработанные именно в рамках этого прохождения, а не все ранее заработанные бэджи

2023-01-10 08:43 UTC, vadimzhukov commented on app/controllers/badges_controller.rb
> +  def add
я предполагал, что т.к. идет обращение к сервису, работающему с моделями бэджей, то и вызываться он должен из контроллера badge_controller. Ок, перетащу в test_passage_controller

2023-01-10 08:47 UTC, vadimzhukov commented on app/controllers/users_controller.rb
> +  def rewards
по мне это разные логически страницы - заработанное и потенциально существующее, пока так оставлю, ок? )

2023-01-10 08:50 UTC, vadimzhukov commented on app/models/test_passage.rb
> +    self.successfully = true if successful?
исправлено

2023-01-10 08:53 UTC, vadimzhukov commented on app/services/reward_service.rb
> +        BadgeRule.where(badge_id: badge).each do |badge_rule|
нет, тут я именно к промежуточной таблице обращаюсь чтобы вытащить из нее значения конкретных параметров для правила для данного badge (parameters_thresholds)

2023-01-10 09:04 UTC, vadimzhukov commented on config/routes.rb
> +  get 'badges/add', to: 'badges#add', as: 'add_badges'
create это по идее создание бэджа, а не присоединение существующего к пользователю его заслужившему. Если принципиально, то могу переделать

2023-01-10 10:04 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @badges = current_user.badges.select{|b| UserBadge.where("test_passage_id = ?", @test_passage.id).pluck('badge_id').include?(b.id)}
это тебе может сервис вернуть, выданные бейджи. он же их как раз перебирает, и чтобы не делать второй запрос на то чтобы получить только что созданные, делаешь так что бы сервис вернул то что создает

2023-01-10 10:10 UTC, vadimzhukov commented on app/services/reward_service.rb
> +        BadgeRule.where(badge_id: badge).each do |badge_rule|
исправил на ассоциацию badge.badge_rules

2023-01-11 11:30 UTC, merged