feat: урок8 views, layouts_templates_partials, helpers
vadimzhukov/TestGuru pull request #9
Opened 2022-08-24 12:41 UTC by vadimzhukov

добавлены view для тестов и вопросов, включая списки, просмотр, редактирование, удаление. Добавлена навигация. Добавлен футер.

2022-08-24 19:01 UTC, BubuntuClu requested changes

2022-08-24 19:01 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
ты создаешь вопрос через ассоциацию, test_id не нужен

2022-08-24 19:01 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def index
зачем такой экшен нужен? и как ты в него попадаешь вообще?

2022-08-24 19:01 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def question_parameters
обычно такие методы называют просто `*_params`, не пишут `parameters`

2022-08-24 19:01 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<h2><%= question_header(:new, @test) %> </h2>
какой толк от такого метода, если ты ему указываешь сам через параметр что отрисовать? подавай в этот метод только объект вопроса и по состоянию вопроса определяй какой заголовок подставить. помогут тебе методы `new_record?/persisted?`

2022-08-24 19:01 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
возвращай отсюда сразу хэлпер `link_to`

2022-08-24 19:06 UTC, vadimzhukov commented on app/controllers/application_controller.rb
> +  def index
Это я забыл про роут root и пытался индекс главной сразу направить на тесты )

2022-08-24 19:17 UTC, vadimzhukov commented on app/views/questions/new.html.erb
> +<h2><%= question_header(:new, @test) %> </h2>
persisted? понятно, а new_record? зачем тут?

2022-08-24 19:17 UTC, vadimzhukov commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
fixed

2022-08-24 19:17 UTC, vadimzhukov commented on app/controllers/questions_controller.rb
>    def question_parameters
fixed

2022-08-24 19:18 UTC, vadimzhukov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
fixed

2022-08-25 06:23 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<h2><%= question_header(:new, @test) %> </h2>
это два противоположных метода. любой из них можно использовать, на твой выбор.

2022-08-25 07:55 UTC, merged